name: Local Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and restart containers
        shell: powershell
        run: |
          # переходим в каталог репо
          cd $Env:GITHUB_WORKSPACE
          # останавливаем старые контейнеры (не упадёт, если их нет)
          docker compose down
          # пересобираем и запускаем
          docker compose up -d --build
